<?php
define('VOLATILITY_TABLE', 'volatility');
define('VOLATILITY_ID', 'volatility_id');
define('VOLATILITY_SYMBOL', 'volatility_symbol');
define('VOLATILITY_TIME', 'volatility_time');
define('VOLATILITY_1D_HIGH_LOW_AVG3D_VALUE', 'volatility_1d_high_low_avg3d_value');
define('VOLATILITY_1D_HIGH_HIGH_AVG3D_VALUE', 'volatility_1d_high_high_avg3d_value');
define('VOLATILITY_1D_LOW_LOW_AVG3D_VALUE', 'volatility_1d_low_low_avg3d_value');
define('VOLATILITY_1D_HIGH_LOW_AVG7D_VALUE', 'volatility_1d_high_low_avg7d_value');
define('VOLATILITY_1D_HIGH_HIGH_AVG7D_VALUE', 'volatility_1d_high_high_avg7d_value');
define('VOLATILITY_1D_LOW_LOW_AVG7D_VALUE', 'volatility_1d_low_low_avg7d_value');
define('VOLATILITY_4H_HIGH_LOW_AVG3D_VALUE', 'volatility_4h_high_low_avg3d_value');
define('VOLATILITY_4H_HIGH_HIGH_AVG3D_VALUE', 'volatility_4h_high_high_avg3d_value');
define('VOLATILITY_4H_LOW_LOW_AVG3D_VALUE', 'volatility_4h_low_low_avg3d_value');
define('VOLATILITY_4H_HIGH_LOW_AVG7D_VALUE', 'volatility_4h_high_low_avg7d_value');
define('VOLATILITY_4H_HIGH_HIGH_AVG7D_VALUE', 'volatility_4h_high_high_avg7d_value');
define('VOLATILITY_4H_LOW_LOW_AVG7D_VALUE', 'volatility_4h_low_low_avg7d_value');
define('VOLATILITY_1D_HIGH_LOW_AVG3D_RANK', 'volatility_1d_high_low_avg3d_rank');
define('VOLATILITY_1D_HIGH_HIGH_AVG3D_RANK', 'volatility_1d_high_high_avg3d_rank');
define('VOLATILITY_1D_LOW_LOW_AVG3D_RANK', 'volatility_1d_low_low_avg3d_rank');
define('VOLATILITY_1D_HIGH_LOW_AVG7D_RANK', 'volatility_1d_high_low_avg7d_rank');
define('VOLATILITY_1D_HIGH_HIGH_AVG7D_RANK', 'volatility_1d_high_high_avg7d_rank');
define('VOLATILITY_1D_LOW_LOW_AVG7D_RANK', 'volatility_1d_low_low_avg7d_rank');
define('VOLATILITY_4H_HIGH_LOW_AVG3D_RANK', 'volatility_4h_high_low_avg3d_rank');
define('VOLATILITY_4H_HIGH_HIGH_AVG3D_RANK', 'volatility_4h_high_high_avg3d_rank');
define('VOLATILITY_4H_LOW_LOW_AVG3D_RANK', 'volatility_4h_low_low_avg3d_rank');
define('VOLATILITY_4H_HIGH_LOW_AVG7D_RANK', 'volatility_4h_high_low_avg7d_rank');
define('VOLATILITY_4H_HIGH_HIGH_AVG7D_RANK', 'volatility_4h_high_high_avg7d_rank');
define('VOLATILITY_4H_LOW_LOW_AVG7D_RANK', 'volatility_4h_low_low_avg7d_rank');

define('VOLATILITY_4H_CLOSE_LOW_AVG3D_VALUE', 'volatility_4h_close_low_avg3d_value');
define('VOLATILITY_4H_CLOSE_LOW_AVG7D_VALUE', 'volatility_4h_close_low_avg7d_value');
define('VOLATILITY_1D_CLOSE_LOW_AVG3D_VALUE', 'volatility_1d_close_low_avg3d_value');
define('VOLATILITY_1D_CLOSE_LOW_AVG7D_VALUE', 'volatility_1d_close_low_avg7d_value');
define('VOLATILITY_4H_CLOSE_LOW_AVG3D_RANK', 'volatility_4h_close_low_avg3d_rank');
define('VOLATILITY_4H_CLOSE_LOW_AVG7D_RANK', 'volatility_4h_close_low_avg7d_rank');
define('VOLATILITY_1D_CLOSE_LOW_AVG3D_RANK', 'volatility_1d_close_low_avg3d_rank');
define('VOLATILITY_1D_CLOSE_LOW_AVG7D_RANK', 'volatility_1d_close_low_avg7d_rank');

