# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class LabCandle15M(models.Model):
    lab_candle_15m_id = models.AutoField(primary_key=True)
    lab_candle_15m_time = models.BigIntegerField()
    lab_candle_15m_symbol = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_15m_open_time = models.FloatField(blank=True, null=True)
    lab_candle_15m_close_time = models.FloatField(blank=True, null=True)
    lab_candle_15m_open = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_15m_close = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_15m_high = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_15m_low = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_15m_trades = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_15m_volume = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_15m_ema5 = models.FloatField(blank=True, null=True)
    lab_candle_15m_ema9 = models.FloatField(blank=True, null=True)
    lab_candle_15m_ema12 = models.FloatField(blank=True, null=True)
    lab_candle_15m_ema13 = models.FloatField(blank=True, null=True)
    lab_candle_15m_ema26 = models.FloatField(blank=True, null=True)
    lab_candle_15m_macd = models.FloatField(blank=True, null=True)
    lab_candle_15m_signal = models.FloatField(blank=True, null=True)
    lab_candle_15m_histogram = models.FloatField(blank=True, null=True)
    lab_candle_15m_signal7 = models.FloatField(blank=True, null=True)
    lab_candle_15m_histogram7 = models.FloatField(blank=True, null=True)
    lab_candle_15m_signal4 = models.FloatField(blank=True, null=True)
    lab_candle_15m_histogram4 = models.FloatField(blank=True, null=True)
    lab_candle_15m_signal5 = models.FloatField(blank=True, null=True)
    lab_candle_15m_histogram5 = models.FloatField(blank=True, null=True)
    lab_candle_15m_signal6 = models.FloatField(blank=True, null=True)
    lab_candle_15m_histogram6 = models.FloatField(blank=True, null=True)
    lab_candle_15m_signal2 = models.FloatField(blank=True, null=True)
    lab_candle_15m_histogram2 = models.FloatField(blank=True, null=True)
    lab_candle_15m_signal3 = models.FloatField(blank=True, null=True)
    lab_candle_15m_histogram3 = models.FloatField(blank=True, null=True)
    lab_candle_15m_startpoint = models.IntegerField(blank=True, null=True)
    lab_candle_15m_avgu14 = models.FloatField(blank=True, null=True)
    lab_candle_15m_avgd14 = models.FloatField(blank=True, null=True)
    lab_candle_15m_rsi14 = models.FloatField(blank=True, null=True)
    lab_candle_15m_rsi_ema9 = models.FloatField(blank=True, null=True)
    lab_candle_15m_rsi_ema5 = models.FloatField(blank=True, null=True)
    lab_candle_15m_rsi_ema4 = models.FloatField(blank=True, null=True)
    lab_candle_15m_rsi_wma = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'lab_candle_15m'
        unique_together = (('lab_candle_15m_id', 'lab_candle_15m_time'),)


class LabCandle1D(models.Model):
    lab_candle_1d_id = models.AutoField(primary_key=True)
    lab_candle_1d_time = models.BigIntegerField()
    lab_candle_1d_symbol = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_1d_open_time = models.FloatField(blank=True, null=True)
    lab_candle_1d_close_time = models.FloatField(blank=True, null=True)
    lab_candle_1d_open = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_1d_close = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_1d_high = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_1d_low = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_1d_trades = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_1d_volume = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_1d_ema5 = models.FloatField(blank=True, null=True)
    lab_candle_1d_ema9 = models.FloatField(blank=True, null=True)
    lab_candle_1d_ema12 = models.FloatField(blank=True, null=True)
    lab_candle_1d_ema13 = models.FloatField(blank=True, null=True)
    lab_candle_1d_ema26 = models.FloatField(blank=True, null=True)
    lab_candle_1d_macd = models.FloatField(blank=True, null=True)
    lab_candle_1d_signal = models.FloatField(blank=True, null=True)
    lab_candle_1d_histogram = models.FloatField(blank=True, null=True)
    lab_candle_1d_signal7 = models.FloatField(blank=True, null=True)
    lab_candle_1d_histogram7 = models.FloatField(blank=True, null=True)
    lab_candle_1d_signal4 = models.FloatField(blank=True, null=True)
    lab_candle_1d_histogram4 = models.FloatField(blank=True, null=True)
    lab_candle_1d_signal5 = models.FloatField(blank=True, null=True)
    lab_candle_1d_histogram5 = models.FloatField(blank=True, null=True)
    lab_candle_1d_signal6 = models.FloatField(blank=True, null=True)
    lab_candle_1d_histogram6 = models.FloatField(blank=True, null=True)
    lab_candle_1d_signal2 = models.FloatField(blank=True, null=True)
    lab_candle_1d_histogram2 = models.FloatField(blank=True, null=True)
    lab_candle_1d_signal3 = models.FloatField(blank=True, null=True)
    lab_candle_1d_histogram3 = models.FloatField(blank=True, null=True)
    lab_candle_1d_startpoint = models.IntegerField(blank=True, null=True)
    lab_candle_1d_avgu14 = models.FloatField(blank=True, null=True)
    lab_candle_1d_avgd14 = models.FloatField(blank=True, null=True)
    lab_candle_1d_rsi14 = models.FloatField(blank=True, null=True)
    lab_candle_1d_rsi_ema9 = models.FloatField(blank=True, null=True)
    lab_candle_1d_rsi_ema5 = models.FloatField(blank=True, null=True)
    lab_candle_1d_rsi_ema4 = models.FloatField(blank=True, null=True)
    lab_candle_1d_rsi_wma = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'lab_candle_1d'
        unique_together = (('lab_candle_1d_id', 'lab_candle_1d_time'),)


class LabCandle1H(models.Model):
    lab_candle_1h_id = models.AutoField(primary_key=True)
    lab_candle_1h_time = models.BigIntegerField()
    lab_candle_1h_symbol = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_1h_open_time = models.FloatField(blank=True, null=True)
    lab_candle_1h_close_time = models.FloatField(blank=True, null=True)
    lab_candle_1h_open = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_1h_close = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_1h_high = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_1h_low = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_1h_trades = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_1h_volume = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_1h_ema5 = models.FloatField(blank=True, null=True)
    lab_candle_1h_ema9 = models.FloatField(blank=True, null=True)
    lab_candle_1h_ema12 = models.FloatField(blank=True, null=True)
    lab_candle_1h_ema13 = models.FloatField(blank=True, null=True)
    lab_candle_1h_ema26 = models.FloatField(blank=True, null=True)
    lab_candle_1h_macd = models.FloatField(blank=True, null=True)
    lab_candle_1h_signal = models.FloatField(blank=True, null=True)
    lab_candle_1h_histogram = models.FloatField(blank=True, null=True)
    lab_candle_1h_signal7 = models.FloatField(blank=True, null=True)
    lab_candle_1h_histogram7 = models.FloatField(blank=True, null=True)
    lab_candle_1h_signal4 = models.FloatField(blank=True, null=True)
    lab_candle_1h_histogram4 = models.FloatField(blank=True, null=True)
    lab_candle_1h_signal5 = models.FloatField(blank=True, null=True)
    lab_candle_1h_histogram5 = models.FloatField(blank=True, null=True)
    lab_candle_1h_signal6 = models.FloatField(blank=True, null=True)
    lab_candle_1h_histogram6 = models.FloatField(blank=True, null=True)
    lab_candle_1h_signal2 = models.FloatField(blank=True, null=True)
    lab_candle_1h_histogram2 = models.FloatField(blank=True, null=True)
    lab_candle_1h_signal3 = models.FloatField(blank=True, null=True)
    lab_candle_1h_histogram3 = models.FloatField(blank=True, null=True)
    lab_candle_1h_startpoint = models.IntegerField(blank=True, null=True)
    lab_candle_1h_avgu14 = models.FloatField(blank=True, null=True)
    lab_candle_1h_avgd14 = models.FloatField(blank=True, null=True)
    lab_candle_1h_rsi14 = models.FloatField(blank=True, null=True)
    lab_candle_1h_rsi_ema9 = models.FloatField(blank=True, null=True)
    lab_candle_1h_rsi_ema5 = models.FloatField(blank=True, null=True)
    lab_candle_1h_rsi_ema4 = models.FloatField(blank=True, null=True)
    lab_candle_1h_rsi_wma = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'lab_candle_1h'
        unique_together = (('lab_candle_1h_id', 'lab_candle_1h_time'),)


class LabCandle1M(models.Model):
    lab_candle_1m_id = models.AutoField(primary_key=True)
    lab_candle_1m_time = models.BigIntegerField()
    lab_candle_1m_symbol = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_1m_open_time = models.FloatField(blank=True, null=True)
    lab_candle_1m_close_time = models.FloatField(blank=True, null=True)
    lab_candle_1m_open = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_1m_close = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_1m_high = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_1m_low = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_1m_trades = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_1m_volume = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_1m_ema5 = models.FloatField(blank=True, null=True)
    lab_candle_1m_ema9 = models.FloatField(blank=True, null=True)
    lab_candle_1m_ema12 = models.FloatField(blank=True, null=True)
    lab_candle_1m_ema13 = models.FloatField(blank=True, null=True)
    lab_candle_1m_ema26 = models.FloatField(blank=True, null=True)
    lab_candle_1m_macd = models.FloatField(blank=True, null=True)
    lab_candle_1m_signal = models.FloatField(blank=True, null=True)
    lab_candle_1m_histogram = models.FloatField(blank=True, null=True)
    lab_candle_1m_signal7 = models.FloatField(blank=True, null=True)
    lab_candle_1m_histogram7 = models.FloatField(blank=True, null=True)
    lab_candle_1m_signal4 = models.FloatField(blank=True, null=True)
    lab_candle_1m_histogram4 = models.FloatField(blank=True, null=True)
    lab_candle_1m_signal5 = models.FloatField(blank=True, null=True)
    lab_candle_1m_histogram5 = models.FloatField(blank=True, null=True)
    lab_candle_1m_signal6 = models.FloatField(blank=True, null=True)
    lab_candle_1m_histogram6 = models.FloatField(blank=True, null=True)
    lab_candle_1m_signal2 = models.FloatField(blank=True, null=True)
    lab_candle_1m_histogram2 = models.FloatField(blank=True, null=True)
    lab_candle_1m_signal3 = models.FloatField(blank=True, null=True)
    lab_candle_1m_histogram3 = models.FloatField(blank=True, null=True)
    lab_candle_1m_startpoint = models.IntegerField(blank=True, null=True)
    lab_candle_1m_avgu14 = models.FloatField(blank=True, null=True)
    lab_candle_1m_avgd14 = models.FloatField(blank=True, null=True)
    lab_candle_1m_rsi14 = models.FloatField(blank=True, null=True)
    lab_candle_1m_rsi_ema9 = models.FloatField(blank=True, null=True)
    lab_candle_1m_rsi_ema5 = models.FloatField(blank=True, null=True)
    lab_candle_1m_rsi_ema4 = models.FloatField(blank=True, null=True)
    lab_candle_1m_rsi_wma = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'lab_candle_1m'
        unique_together = (('lab_candle_1m_id', 'lab_candle_1m_time'),)


class LabCandle1W(models.Model):
    lab_candle_1w_id = models.AutoField(primary_key=True)
    lab_candle_1w_time = models.BigIntegerField()
    lab_candle_1w_symbol = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_1w_open_time = models.FloatField(blank=True, null=True)
    lab_candle_1w_close_time = models.FloatField(blank=True, null=True)
    lab_candle_1w_open = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_1w_close = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_1w_high = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_1w_low = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_1w_trades = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_1w_volume = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_1w_ema5 = models.FloatField(blank=True, null=True)
    lab_candle_1w_ema9 = models.FloatField(blank=True, null=True)
    lab_candle_1w_ema12 = models.FloatField(blank=True, null=True)
    lab_candle_1w_ema13 = models.FloatField(blank=True, null=True)
    lab_candle_1w_ema26 = models.FloatField(blank=True, null=True)
    lab_candle_1w_macd = models.FloatField(blank=True, null=True)
    lab_candle_1w_signal = models.FloatField(blank=True, null=True)
    lab_candle_1w_histogram = models.FloatField(blank=True, null=True)
    lab_candle_1w_signal7 = models.FloatField(blank=True, null=True)
    lab_candle_1w_histogram7 = models.FloatField(blank=True, null=True)
    lab_candle_1w_signal4 = models.FloatField(blank=True, null=True)
    lab_candle_1w_histogram4 = models.FloatField(blank=True, null=True)
    lab_candle_1w_signal5 = models.FloatField(blank=True, null=True)
    lab_candle_1w_histogram5 = models.FloatField(blank=True, null=True)
    lab_candle_1w_signal6 = models.FloatField(blank=True, null=True)
    lab_candle_1w_histogram6 = models.FloatField(blank=True, null=True)
    lab_candle_1w_signal2 = models.FloatField(blank=True, null=True)
    lab_candle_1w_histogram2 = models.FloatField(blank=True, null=True)
    lab_candle_1w_signal3 = models.FloatField(blank=True, null=True)
    lab_candle_1w_histogram3 = models.FloatField(blank=True, null=True)
    lab_candle_1w_startpoint = models.IntegerField(blank=True, null=True)
    lab_candle_1w_avgu14 = models.FloatField(blank=True, null=True)
    lab_candle_1w_avgd14 = models.FloatField(blank=True, null=True)
    lab_candle_1w_rsi14 = models.FloatField(blank=True, null=True)
    lab_candle_1w_rsi_ema9 = models.FloatField(blank=True, null=True)
    lab_candle_1w_rsi_ema5 = models.FloatField(blank=True, null=True)
    lab_candle_1w_rsi_ema4 = models.FloatField(blank=True, null=True)
    lab_candle_1w_rsi_wma = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'lab_candle_1w'
        unique_together = (('lab_candle_1w_id', 'lab_candle_1w_time'),)


class LabCandle3M(models.Model):
    lab_candle_3m_id = models.AutoField(primary_key=True)
    lab_candle_3m_time = models.BigIntegerField()
    lab_candle_3m_symbol = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_3m_open_time = models.FloatField(blank=True, null=True)
    lab_candle_3m_close_time = models.FloatField(blank=True, null=True)
    lab_candle_3m_open = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_3m_close = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_3m_high = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_3m_low = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_3m_trades = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_3m_volume = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_3m_ema5 = models.FloatField(blank=True, null=True)
    lab_candle_3m_ema9 = models.FloatField(blank=True, null=True)
    lab_candle_3m_ema12 = models.FloatField(blank=True, null=True)
    lab_candle_3m_ema13 = models.FloatField(blank=True, null=True)
    lab_candle_3m_ema26 = models.FloatField(blank=True, null=True)
    lab_candle_3m_macd = models.FloatField(blank=True, null=True)
    lab_candle_3m_signal = models.FloatField(blank=True, null=True)
    lab_candle_3m_histogram = models.FloatField(blank=True, null=True)
    lab_candle_3m_signal7 = models.FloatField(blank=True, null=True)
    lab_candle_3m_histogram7 = models.FloatField(blank=True, null=True)
    lab_candle_3m_signal4 = models.FloatField(blank=True, null=True)
    lab_candle_3m_histogram4 = models.FloatField(blank=True, null=True)
    lab_candle_3m_signal5 = models.FloatField(blank=True, null=True)
    lab_candle_3m_histogram5 = models.FloatField(blank=True, null=True)
    lab_candle_3m_signal6 = models.FloatField(blank=True, null=True)
    lab_candle_3m_histogram6 = models.FloatField(blank=True, null=True)
    lab_candle_3m_signal2 = models.FloatField(blank=True, null=True)
    lab_candle_3m_histogram2 = models.FloatField(blank=True, null=True)
    lab_candle_3m_signal3 = models.FloatField(blank=True, null=True)
    lab_candle_3m_histogram3 = models.FloatField(blank=True, null=True)
    lab_candle_3m_startpoint = models.IntegerField(blank=True, null=True)
    lab_candle_3m_avgu14 = models.FloatField(blank=True, null=True)
    lab_candle_3m_avgd14 = models.FloatField(blank=True, null=True)
    lab_candle_3m_rsi14 = models.FloatField(blank=True, null=True)
    lab_candle_3m_rsi_ema9 = models.FloatField(blank=True, null=True)
    lab_candle_3m_rsi_ema5 = models.FloatField(blank=True, null=True)
    lab_candle_3m_rsi_ema4 = models.FloatField(blank=True, null=True)
    lab_candle_3m_rsi_wma = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'lab_candle_3m'
        unique_together = (('lab_candle_3m_id', 'lab_candle_3m_time'),)


class LabCandle4H(models.Model):
    lab_candle_4h_id = models.AutoField(primary_key=True)
    lab_candle_4h_time = models.BigIntegerField()
    lab_candle_4h_symbol = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_4h_open_time = models.FloatField(blank=True, null=True)
    lab_candle_4h_close_time = models.FloatField(blank=True, null=True)
    lab_candle_4h_open = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_4h_close = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_4h_high = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_4h_low = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_4h_trades = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_4h_volume = models.CharField(max_length=150, blank=True, null=True)
    lab_candle_4h_ema5 = models.FloatField(blank=True, null=True)
    lab_candle_4h_ema9 = models.FloatField(blank=True, null=True)
    lab_candle_4h_ema12 = models.FloatField(blank=True, null=True)
    lab_candle_4h_ema13 = models.FloatField(blank=True, null=True)
    lab_candle_4h_ema26 = models.FloatField(blank=True, null=True)
    lab_candle_4h_macd = models.FloatField(blank=True, null=True)
    lab_candle_4h_signal = models.FloatField(blank=True, null=True)
    lab_candle_4h_histogram = models.FloatField(blank=True, null=True)
    lab_candle_4h_signal7 = models.FloatField(blank=True, null=True)
    lab_candle_4h_histogram7 = models.FloatField(blank=True, null=True)
    lab_candle_4h_signal4 = models.FloatField(blank=True, null=True)
    lab_candle_4h_histogram4 = models.FloatField(blank=True, null=True)
    lab_candle_4h_signal5 = models.FloatField(blank=True, null=True)
    lab_candle_4h_histogram5 = models.FloatField(blank=True, null=True)
    lab_candle_4h_signal6 = models.FloatField(blank=True, null=True)
    lab_candle_4h_histogram6 = models.FloatField(blank=True, null=True)
    lab_candle_4h_signal2 = models.FloatField(blank=True, null=True)
    lab_candle_4h_histogram2 = models.FloatField(blank=True, null=True)
    lab_candle_4h_signal3 = models.FloatField(blank=True, null=True)
    lab_candle_4h_histogram3 = models.FloatField(blank=True, null=True)
    lab_candle_4h_startpoint = models.IntegerField(blank=True, null=True)
    lab_candle_4h_avgu14 = models.FloatField(blank=True, null=True)
    lab_candle_4h_avgd14 = models.FloatField(blank=True, null=True)
    lab_candle_4h_rsi14 = models.FloatField(blank=True, null=True)
    lab_candle_4h_rsi_ema9 = models.FloatField(blank=True, null=True)
    lab_candle_4h_rsi_ema5 = models.FloatField(blank=True, null=True)
    lab_candle_4h_rsi_ema4 = models.FloatField(blank=True, null=True)
    lab_candle_4h_rsi_wma = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'lab_candle_4h'
        unique_together = (('lab_candle_4h_id', 'lab_candle_4h_time'),)
