"""Metadata for Alpha Studio AST Builder features and operators."""
from typing import Any, Dict, List

FEATURES_CATALOG: List[Dict[str, Any]] = [
    {
        "id": "execution_1m_ohlcv",
        "name": "1m Execution OHLCV",
        "category": "Execution Frame",
        "frame": "1m",
        "description": "Các cột nến 1 phút dùng để khớp lệnh và kiểm tra điều kiện vào/thoát.",
        "columns": ["open", "high", "low", "close", "volume"],
        "nodes": [
            {"label": "1m Open", "node": {"frame": "1m", "column": "open", "index": "0"}},
            {"label": "1m High", "node": {"frame": "1m", "column": "high", "index": "0"}},
            {"label": "1m Low", "node": {"frame": "1m", "column": "low", "index": "0"}},
            {"label": "1m Close", "node": {"frame": "1m", "column": "close", "index": "0"}},
            {"label": "1m Volume", "node": {"frame": "1m", "column": "volume", "index": "0"}},
        ],
    },
    {
        "id": "context_4h_ohlcv",
        "name": "4h Context OHLCV",
        "category": "Context Frame",
        "frame": "4h",
        "description": "Các cột nến 4 giờ được merge backward vào từng nến 1m để làm bối cảnh xu hướng/biên độ.",
        "columns": ["open", "high", "low", "close", "volume"],
        "nodes": [
            {"label": "4h Open", "node": {"frame": "4h", "column": "open", "index": "0"}},
            {"label": "4h High", "node": {"frame": "4h", "column": "high", "index": "0"}},
            {"label": "4h Low", "node": {"frame": "4h", "column": "low", "index": "0"}},
            {"label": "4h Close", "node": {"frame": "4h", "column": "close", "index": "0"}},
            {"label": "4h Volume", "node": {"frame": "4h", "column": "volume", "index": "0"}},
        ],
    },
    {
        "id": "context_4h_atr_keltner",
        "name": "4h ATR / Keltner",
        "category": "Volatility",
        "frame": "4h",
        "description": "ATR và Keltner Channels được BacktestEngine tính nhẹ từ OHLCV 4h khi chạy Studio.",
        "columns": ["atr", "atr14", "atr17", "atr20", "kup17_05", "kmid17_05", "klo17_05", "kup20_15", "kmid20_15", "klo20_15"],
        "nodes": [
            {"label": "4h ATR", "node": {"frame": "4h", "column": "atr", "index": "0"}},
            {"label": "4h Keltner Upper 17/0.5", "node": {"frame": "4h", "column": "kup17_05", "index": "0"}},
            {"label": "4h Keltner Mid 17/0.5", "node": {"frame": "4h", "column": "kmid17_05", "index": "0"}},
            {"label": "4h Keltner Lower 17/0.5", "node": {"frame": "4h", "column": "klo17_05", "index": "0"}},
            {"label": "4h Keltner Upper 20/1.5", "node": {"frame": "4h", "column": "kup20_15", "index": "0"}},
            {"label": "4h Keltner Mid 20/1.5", "node": {"frame": "4h", "column": "kmid20_15", "index": "0"}},
            {"label": "4h Keltner Lower 20/1.5", "node": {"frame": "4h", "column": "klo20_15", "index": "0"}},
        ],
    },
    {
        "id": "xnoquant_like_archetypes",
        "name": "Strategy Archetypes",
        "category": "Research Patterns",
        "description": "Các pattern NoraBT đang mô phỏng được bằng AST hiện tại: breakout, channel flow, mean reversion và regime filter.",
        "columns": [],
        "nodes": [
            {"label": "Trend breakout", "node": {"pattern": "1m breakout above 4h high with optional volume filter"}},
            {"label": "Volatility channel", "node": {"pattern": "Keltner upper/lower breakout or reversion"}},
            {"label": "Mean reversion", "node": {"pattern": "pierce outer band then exit near mid band"}},
            {"label": "Dual regime", "node": {"pattern": "4h regime confirmation before 1m execution"}},
        ],
    },
    {
        "id": "value_nodes",
        "name": "Value Nodes",
        "category": "Builder Primitives",
        "description": "Các node giá trị mà LogicEvaluator hỗ trợ trực tiếp trong AST.",
        "columns": [],
        "nodes": [
            {"label": "Constant number", "node": 1.0},
            {"label": "Calculate", "node": {"type": "calculate", "number_1": {"frame": "1m", "column": "close", "index": "0"}, "logic": "*", "number_2": 1.01, "multiply": 1.0}},
            {"label": "Min", "node": {"type": "min", "numbers": [{"frame": "1m", "column": "low", "index": "0"}, {"frame": "4h", "column": "low", "index": "0"}]}},
            {"label": "Max", "node": {"type": "max", "numbers": [{"frame": "1m", "column": "high", "index": "0"}, {"frame": "4h", "column": "high", "index": "0"}]}},
        ],
    },
]

OPERATORS_CATALOG: List[Dict[str, Any]] = [
    {
        "id": "comparison",
        "name": "Comparison",
        "category": "Condition",
        "description": "So sánh hai value nodes trong triplet [left, operator, right].",
        "operators": [">", "<", ">=", "<=", "==", "!="],
        "example": [{"frame": "1m", "column": "close", "index": "0"}, ">", {"frame": "4h", "column": "high", "index": "0"}],
    },
    {
        "id": "or_and_tree",
        "name": "OR of AND groups",
        "category": "Condition",
        "description": "Mỗi condition là OR-list; mỗi OR group là danh sách các điều kiện AND.",
        "example": [[[{"frame": "1m", "column": "close", "index": "0"}, ">", {"frame": "4h", "column": "high", "index": "0"}]]],
    },
    {
        "id": "calculate",
        "name": "Calculate node",
        "category": "Math",
        "description": "Tính number_1 logic number_2 rồi nhân multiply; hỗ trợ +, -, *, /.",
        "operators": ["+", "-", "*", "/"],
        "example": {"type": "calculate", "number_1": {"frame": "4h", "column": "close", "index": "0"}, "logic": "*", "number_2": 1.01, "multiply": 1.0},
    },
    {
        "id": "auto_mine_roadmap",
        "name": "Auto Mine Roadmap",
        "category": "Mining",
        "description": "Các toán tử ts_delay/ts_delta/ts_rank/ts_zscore/cross_above cần dữ liệu window/index history trước khi bật thật trong canonical engine.",
        "operators": ["ts_delay", "ts_delta", "ts_min", "ts_max", "ts_rank", "ts_zscore", "cross_above", "cross_below"],
        "example": {"planned": "cross_above(close, ema20) AND ts_rank(volume, 20) > 0.8"},
    },
    {
        "id": "min_max",
        "name": "Min / Max nodes",
        "category": "Math",
        "description": "Lấy min hoặc max của danh sách value nodes hữu hạn.",
        "operators": ["min", "max"],
        "example": {"type": "max", "numbers": [{"frame": "1m", "column": "high", "index": "0"}, {"frame": "4h", "column": "high", "index": "0"}]},
    },
]
