# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
# Custom for Mongo by LIN.
from djongo import models


class Busd(models.Model):
    _id = models.AutoField(primary_key=True)
    symbol = models.CharField(max_length=150, blank=True, null=True)
    tran_time = models.BigIntegerField(blank=True, null=True)
    event_time = models.BigIntegerField(blank=True, null=True)
    ready_time = models.BigIntegerField(blank=True, null=True)
    stable_time = models.IntegerField(blank=True, null=True)
    timestamp = models.IntegerField(blank=True, null=True)
    BU = models.FloatField(blank=True, null=True)
    SD = models.FloatField(blank=True, null=True)
    BU_15 = models.FloatField(blank=True, null=True)
    SD_15 = models.FloatField(blank=True, null=True)
    BU_15_300 = models.FloatField(blank=True, null=True)
    SD_15_300 = models.FloatField(blank=True, null=True)
    BU_60 = models.FloatField(blank=True, null=True)
    SD_60 = models.FloatField(blank=True, null=True)
    BU_60_1200 = models.FloatField(blank=True, null=True)
    SD_60_1200 = models.FloatField(blank=True, null=True)
    BU_240 = models.FloatField(blank=True, null=True)
    SD_240 = models.FloatField(blank=True, null=True)
    BU_240_4800 = models.FloatField(blank=True, null=True)
    SD_240_4800 = models.FloatField(blank=True, null=True)
    BU_1440 = models.FloatField(blank=True, null=True)
    SD_1440 = models.FloatField(blank=True, null=True)
    BU_1440_28800 = models.FloatField(blank=True, null=True)
    SD_1440_28800 = models.FloatField(blank=True, null=True)
    BU_15_300_3_SUM = models.FloatField(blank=True, null=True)
    BU_15_300_3_FAST = models.FloatField(blank=True, null=True)
    BU_15_300_3_SLOW = models.FloatField(blank=True, null=True)
    BU_15_300_3_SMOOTH = models.FloatField(blank=True, null=True)
    BU_15_300_3_MACD = models.FloatField(blank=True, null=True)
    BU_15_300_3_MACDh = models.FloatField(blank=True, null=True)
    SD_15_300_3_SUM = models.FloatField(blank=True, null=True)
    SD_15_300_3_FAST = models.FloatField(blank=True, null=True)
    SD_15_300_3_SLOW = models.FloatField(blank=True, null=True)
    SD_15_300_3_SMOOTH = models.FloatField(blank=True, null=True)
    SD_15_300_3_MACD = models.FloatField(blank=True, null=True)
    SD_15_300_3_MACDh = models.FloatField(blank=True, null=True)
    BUSD_15_300_3 = models.FloatField(blank=True, null=True)
    BUSD_15_300_3_FAST = models.FloatField(blank=True, null=True)
    BUSD_15_300_3_SLOW = models.FloatField(blank=True, null=True)
    BUSD_15_300_3_SMOOTH = models.FloatField(blank=True, null=True)
    BUSD_15_300_3_MACD = models.FloatField(blank=True, null=True)
    BUSD_15_300_3_MACDh = models.FloatField(blank=True, null=True)
    BUSD_15_300_3_MACDh_p1 = models.FloatField(blank=True, null=True)
    BUSD_15_300_3_MACDh_p2 = models.FloatField(blank=True, null=True)
    BUSD_15_300_3_MACDh_p3 = models.FloatField(blank=True, null=True)
    BUSD_15_300_3_MACDh_p4 = models.FloatField(blank=True, null=True)
    BU_60_1200_5_SUM = models.FloatField(blank=True, null=True)
    BU_60_1200_5_FAST = models.FloatField(blank=True, null=True)
    BU_60_1200_5_SLOW = models.FloatField(blank=True, null=True)
    BU_60_1200_5_SMOOTH = models.FloatField(blank=True, null=True)
    BU_60_1200_5_MACD = models.FloatField(blank=True, null=True)
    BU_60_1200_5_MACDh = models.FloatField(blank=True, null=True)
    SD_60_1200_5_SUM = models.FloatField(blank=True, null=True)
    SD_60_1200_5_FAST = models.FloatField(blank=True, null=True)
    SD_60_1200_5_SLOW = models.FloatField(blank=True, null=True)
    SD_60_1200_5_SMOOTH = models.FloatField(blank=True, null=True)
    SD_60_1200_5_MACD = models.FloatField(blank=True, null=True)
    SD_60_1200_5_MACDh = models.FloatField(blank=True, null=True)
    BUSD_60_1200_5 = models.FloatField(blank=True, null=True)
    BUSD_60_1200_5_FAST = models.FloatField(blank=True, null=True)
    BUSD_60_1200_5_SLOW = models.FloatField(blank=True, null=True)
    BUSD_60_1200_5_SMOOTH = models.FloatField(blank=True, null=True)
    BUSD_60_1200_5_MACD = models.FloatField(blank=True, null=True)
    BUSD_60_1200_5_MACDh = models.FloatField(blank=True, null=True)
    BUSD_60_1200_5_MACDh_p1 = models.FloatField(blank=True, null=True)
    BUSD_60_1200_5_MACDh_p2 = models.FloatField(blank=True, null=True)
    BUSD_60_1200_5_MACDh_p3 = models.FloatField(blank=True, null=True)
    BUSD_60_1200_5_MACDh_p4 = models.FloatField(blank=True, null=True)
    BU_240_4800_5_SUM = models.FloatField(blank=True, null=True)
    BU_240_4800_5_FAST = models.FloatField(blank=True, null=True)
    BU_240_4800_5_SLOW = models.FloatField(blank=True, null=True)
    BU_240_4800_5_SMOOTH = models.FloatField(blank=True, null=True)
    BU_240_4800_5_MACD = models.FloatField(blank=True, null=True)
    BU_240_4800_5_MACDh = models.FloatField(blank=True, null=True)
    SD_240_4800_5_SUM = models.FloatField(blank=True, null=True)
    SD_240_4800_5_FAST = models.FloatField(blank=True, null=True)
    SD_240_4800_5_SLOW = models.FloatField(blank=True, null=True)
    SD_240_4800_5_SMOOTH = models.FloatField(blank=True, null=True)
    SD_240_4800_5_MACD = models.FloatField(blank=True, null=True)
    SD_240_4800_5_MACDh = models.FloatField(blank=True, null=True)
    BUSD_240_4800_5 = models.FloatField(blank=True, null=True)
    BUSD_240_4800_5_FAST = models.FloatField(blank=True, null=True)
    BUSD_240_4800_5_SLOW = models.FloatField(blank=True, null=True)
    BUSD_240_4800_5_SMOOTH = models.FloatField(blank=True, null=True)
    BUSD_240_4800_5_MACD = models.FloatField(blank=True, null=True)
    BUSD_240_4800_5_MACDh = models.FloatField(blank=True, null=True)
    BUSD_240_4800_5_MACDh_p1 = models.FloatField(blank=True, null=True)
    BUSD_240_4800_5_MACDh_p2 = models.FloatField(blank=True, null=True)
    BUSD_240_4800_5_MACDh_p3 = models.FloatField(blank=True, null=True)
    BUSD_240_4800_5_MACDh_p4 = models.FloatField(blank=True, null=True)
    BU_60_1200_60_SUM = models.FloatField(blank=True, null=True)
    BU_60_1200_60_FAST = models.FloatField(blank=True, null=True)
    BU_60_1200_60_SLOW = models.FloatField(blank=True, null=True)
    BU_60_1200_60_SMOOTH = models.FloatField(blank=True, null=True)
    BU_60_1200_60_MACD = models.FloatField(blank=True, null=True)
    BU_60_1200_60_MACDh = models.FloatField(blank=True, null=True)
    SD_60_1200_60_SUM = models.FloatField(blank=True, null=True)
    SD_60_1200_60_FAST = models.FloatField(blank=True, null=True)
    SD_60_1200_60_SLOW = models.FloatField(blank=True, null=True)
    SD_60_1200_60_SMOOTH = models.FloatField(blank=True, null=True)
    SD_60_1200_60_MACD = models.FloatField(blank=True, null=True)
    SD_60_1200_60_MACDh = models.FloatField(blank=True, null=True)
    BUSD_60_1200_60 = models.FloatField(blank=True, null=True)
    BUSD_60_1200_60_FAST = models.FloatField(blank=True, null=True)
    BUSD_60_1200_60_SLOW = models.FloatField(blank=True, null=True)
    BUSD_60_1200_60_SMOOTH = models.FloatField(blank=True, null=True)
    BUSD_60_1200_60_MACD = models.FloatField(blank=True, null=True)
    BUSD_60_1200_60_MACDh = models.FloatField(blank=True, null=True)
    BUSD_60_1200_60_MACDh_p1 = models.FloatField(blank=True, null=True)
    BUSD_60_1200_60_MACDh_p2 = models.FloatField(blank=True, null=True)
    BUSD_60_1200_60_MACDh_p3 = models.FloatField(blank=True, null=True)
    BUSD_60_1200_60_MACDh_p4 = models.FloatField(blank=True, null=True)
    BU_240_4800_60_SUM = models.FloatField(blank=True, null=True)
    BU_240_4800_60_FAST = models.FloatField(blank=True, null=True)
    BU_240_4800_60_SLOW = models.FloatField(blank=True, null=True)
    BU_240_4800_60_SMOOTH = models.FloatField(blank=True, null=True)
    BU_240_4800_60_MACD = models.FloatField(blank=True, null=True)
    BU_240_4800_60_MACDh = models.FloatField(blank=True, null=True)
    SD_240_4800_60_SUM = models.FloatField(blank=True, null=True)
    SD_240_4800_60_FAST = models.FloatField(blank=True, null=True)
    SD_240_4800_60_SLOW = models.FloatField(blank=True, null=True)
    SD_240_4800_60_SMOOTH = models.FloatField(blank=True, null=True)
    SD_240_4800_60_MACD = models.FloatField(blank=True, null=True)
    SD_240_4800_60_MACDh = models.FloatField(blank=True, null=True)
    BUSD_240_4800_60 = models.FloatField(blank=True, null=True)
    BUSD_240_4800_60_FAST = models.FloatField(blank=True, null=True)
    BUSD_240_4800_60_SLOW = models.FloatField(blank=True, null=True)
    BUSD_240_4800_60_SMOOTH = models.FloatField(blank=True, null=True)
    BUSD_240_4800_60_MACD = models.FloatField(blank=True, null=True)
    BUSD_240_4800_60_MACDh = models.FloatField(blank=True, null=True)
    BUSD_240_4800_60_MACDh_p1 = models.FloatField(blank=True, null=True)
    BUSD_240_4800_60_MACDh_p2 = models.FloatField(blank=True, null=True)
    BUSD_240_4800_60_MACDh_p3 = models.FloatField(blank=True, null=True)
    BUSD_240_4800_60_MACDh_p4 = models.FloatField(blank=True, null=True)
    BU_1440_28800_60_SUM = models.FloatField(blank=True, null=True)
    BU_1440_28800_60_FAST = models.FloatField(blank=True, null=True)
    BU_1440_28800_60_SLOW = models.FloatField(blank=True, null=True)
    BU_1440_28800_60_SMOOTH = models.FloatField(blank=True, null=True)
    BU_1440_28800_60_MACD = models.FloatField(blank=True, null=True)
    BU_1440_28800_60_MACDh = models.FloatField(blank=True, null=True)
    SD_1440_28800_60_SUM = models.FloatField(blank=True, null=True)
    SD_1440_28800_60_FAST = models.FloatField(blank=True, null=True)
    SD_1440_28800_60_SLOW = models.FloatField(blank=True, null=True)
    SD_1440_28800_60_SMOOTH = models.FloatField(blank=True, null=True)
    SD_1440_28800_60_MACD = models.FloatField(blank=True, null=True)
    SD_1440_28800_60_MACDh = models.FloatField(blank=True, null=True)
    BUSD_1440_28800_60 = models.FloatField(blank=True, null=True)
    BUSD_1440_28800_60_FAST = models.FloatField(blank=True, null=True)
    BUSD_1440_28800_60_SLOW = models.FloatField(blank=True, null=True)
    BUSD_1440_28800_60_SMOOTH = models.FloatField(blank=True, null=True)
    BUSD_1440_28800_60_MACD = models.FloatField(blank=True, null=True)
    BUSD_1440_28800_60_MACDh = models.FloatField(blank=True, null=True)
    BUSD_1440_28800_60_MACDh_p1 = models.FloatField(blank=True, null=True)
    BUSD_1440_28800_60_MACDh_p2 = models.FloatField(blank=True, null=True)
    BUSD_1440_28800_60_MACDh_p3 = models.FloatField(blank=True, null=True)
    BUSD_1440_28800_60_MACDh_p4 = models.FloatField(blank=True, null=True)
    timestamp_macd = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'busd'


class OrderBook(models.Model):
    _id = models.AutoField(primary_key=True)
    symbol = models.CharField(max_length=150, blank=True, null=True)
    tran_time = models.BigIntegerField(blank=True, null=True)
    event_time = models.BigIntegerField(blank=True, null=True)
    ready_time = models.FloatField(blank=True, null=True)
    stable_time = models.IntegerField(blank=True, null=True)
    timestamp = models.IntegerField(blank=True, null=True)
    best_ask = models.FloatField(blank=True, null=True)
    best_bid = models.FloatField(blank=True, null=True)
    mid_price = models.FloatField(blank=True, null=True)
    askV_1 = models.FloatField(blank=True, null=True)
    bidV_1 = models.FloatField(blank=True, null=True)
    askV_0_1 = models.FloatField(blank=True, null=True)
    bidV_0_1 = models.FloatField(blank=True, null=True)
    askV_2 = models.FloatField(blank=True, null=True)
    bidV_2 = models.FloatField(blank=True, null=True)
    askV_1_2 = models.FloatField(blank=True, null=True)
    bidV_1_2 = models.FloatField(blank=True, null=True)
    askV_5 = models.FloatField(blank=True, null=True)
    bidV_5 = models.FloatField(blank=True, null=True)
    askV_2_5 = models.FloatField(blank=True, null=True)
    bidV_2_5 = models.FloatField(blank=True, null=True)
    bidV_ma_5 = models.FloatField(blank=True, null=True)
    askV_ma_5 = models.FloatField(blank=True, null=True)
    NetBA_5 = models.FloatField(blank=True, null=True)
    NetBA_std_5 = models.FloatField(blank=True, null=True)
    NetBA_mean_5 = models.FloatField(blank=True, null=True)
    NetBA_BOLU_5 = models.FloatField(blank=True, null=True)
    NetBA_BOLD_5 = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'order_book'
