class OrderStatus:
    STATUS_SENDING = 'SENDING'
    STATUS_SENT = 'SENT'
    STATUS_MATCHED_PART = 'MATCHED_PART'
    STATUS_MATCHED_FULL = 'MATCHED_FULL'
    STATUS_CANCEL_SENT = 'CANCEL_SENT'
    STATUS_EDIT_SENT = 'EDIT_SENT'
    STATUS_CANCELED = 'CANCELED'
    STATUS_ERROR = 'ERROR'
    
class OrderSide:
    SIDE_BUY = 'BUY'
    SIDE_SELL = 'SELL'
    
class OrderType:
    TYPE_LO = "LO"
    TYPE_ATC = "ATC"
    TYPE_ATO = "ATO"
    TYPE_MP = 'MAK'
    
class ActionEnterStatus:
    STATUS_ENTER_WAITTING = 'ENTER_WAITTING'
    STATUS_ENTER_PENDING = 'ENTER_PENDING'
    STATUS_ENTER_PART = 'ENTER_PART'
    STATUS_ENTER_FULL = 'ENTER_FULL'
    STATUS_ENTER_CANCEL = 'ENTER_CANCEL'

class ActionExitStatus:
    STATUS_EXIT_WAITTING = 'EXIT_WAITTING'
    STATUS_EXIT_PENDING = 'EXIT_PENDING'
    STATUS_EXIT_PART = 'EXIT_PART'
    STATUS_EXIT_FULL = 'EXIT_FULL'
    STATUS_EXIT_CANCEL = 'EXIT_CANCEL'
    
class ActionMatchedStatus:
    STATUS_MATCHED = "MATCHED"
    STATUS_EMPTY = "EMPTY"

class ActionCloseStatus:
    STATUS_CLOSE_PENDING = 'CLOSE_PENDING'
    STATUS_CLOSE_FORCE = 'CLOSE_FORCE'
    STATUS_CLOSE_DONE = 'CLOSE_DONE'
    
class ActionMaturityStatus:
    STATUS_MATURITY_RELEASE = 'MATURITY_RELEASE'
    STATUS_MATURITY_RELEASE_PENDING = 'MATURITY_RELEASE_PENDING'
    STATUS_MATURITY_ENTER = 'MATURITY_ENTER'
    STATUS_MATURITY_ENTER_PENDING = 'MATURITY_ENTER_PENDING'
    STATUS_MATURITY_DONE = 'MATURITY_DONE'

    
    
class BillStatus:
    STATUS_COMPLETED = 'COMPLETED'
    STATUS_WAITTING = 'WAITTING'
    STATUS_UNCOMPLETED = 'UNCOMPLETED'
    
class BillActType:
    ACT_TYPE_MAKE_ORDER = 'MAKE_ORDER'
    ACT_TYPE_EXIT_ORDER = 'EXIT_ORDER'
    ACT_TYPE_CLOSE_ORDER = 'CLOSE_ORDER'