"""
Django settings for nora_monitor project.

Generated by 'django-admin startproject' using Django 2.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "agez0=c)@!r=)@cm)(lwmy2=ecq%_ko^0v00fgq3tuolf32oz("

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "models",
    # 'helper',
    "Auto",
    "Console",
    "Agent",
    "Testnet",
    "Backtest",
    "Statistic",
    "Stock",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # 'django.middleware.csrf.CsrfViewMiddleware',
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "nora_monitor.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            "/home/ubuntu/linhvhv/coin_monitor/frontend/build",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "nora_monitor.wsgi.application"


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    },
    "nora_monitor": {
        "ENGINE": "djongo",
        "NAME": "nora_monitor",
        "ENFORCE_SCHEMA": False,
        "CLIENT": {
            #'host': 'mongodb+srv://<username>:<password>@<atlas cluster>/<myFirstDatabase>?retryWrites=true&w=majority'
            # 'host': 'mongodb://nora_monitor:N0ra%40123%21%40%23@103.48.194.135:27017/nora_monitor?retryWrites=true&w=majority'
            "host": "127.0.0.1",
            "port": 27017,
            "username": "nora_monitor",
            "password": "N0ra@123!@#",
            "authSource": "nora_monitor",
            "authMechanism": "SCRAM-SHA-1",
        },
    },
    "nora_realtime": {
        "ENGINE": "djongo",
        "NAME": "realtime_data",
        "ENFORCE_SCHEMA": False,
        "CLIENT": {
            "host": "14.225.16.78",
            "port": 27023,
            "username": "crawler",
            "password": "crawler@1235",
            "authSource": "realtime_data",
            "authMechanism": "SCRAM-SHA-1",
        },
    },
    "testnet": {
        "NAME": "coin_db",
        "ENGINE": "django.db.backends.mysql",
        "CONN_MAX_AGE": 3600,
        "USER": "optimization",
        "PASSWORD": "0timization!@#QWEASDZXC",
        "HOST": "14.225.16.78",
        "PORT": 3324,
    },
    "raw_data": {  # database save raw data of long van 3
        "ENGINE": "djongo",
        "NAME": "raw",
        "ENFORCE_SCHEMA": False,
        "CLIENT": {
            "host": "127.0.0.1",
            "port": 27017,
            "username": "crawler",
            "password": "crawler@1235",
            "authSource": "raw",
            "authMechanism": "SCRAM-SHA-1",
        },
    },
    "raw_data_coinm": {  # database save raw data of long van 3
        "ENGINE": "djongo",
        "NAME": "realtime_data",
        "ENFORCE_SCHEMA": False,
        "CLIENT": {
            "host": "127.0.0.1",
            "port": 27017,
            "username": "crawler",
            "password": "crawler@1235",
            "authSource": "realtime_data",
            "authMechanism": "SCRAM-SHA-1",
        },
    },
    "raw_data_01": {  # database save raw data of long van 3 on HDD
        "ENGINE": "djongo",
        "NAME": "raw_data",
        "ENFORCE_SCHEMA": False,
        "CLIENT": {
            "host": "127.0.0.1",
            "port": 27018,
            "username": "crawler",
            "password": "crawler@1245",
            "authSource": "raw_data",
            "authMechanism": "SCRAM-SHA-1",
        },
    },
    "realtime_data_ssd": {  # database save raw data of long van 3
        "ENGINE": "djongo",
        "NAME": "realtime_data",
        "ENFORCE_SCHEMA": False,
        "CLIENT": {
            "host": "127.0.0.1",
            "port": 27017,
            "username": "administrator",
            "password": "Adm1n@!#$123",
            "authSource": "admin",
            "authMechanism": "SCRAM-SHA-1",
        },
    },
    "realtime_data_hdd": {  # database save raw data of long van 3
        "ENGINE": "djongo",
        "NAME": "realtime_data",
        "ENFORCE_SCHEMA": False,
        "CLIENT": {
            "host": "127.0.0.1",
            "port": 27018,
            "username": "administrator",
            "password": "Adm1n@!#$123",
            "authSource": "admin",
            "authMechanism": "SCRAM-SHA-1",
        },
    },
    "raw_kline1m_future": {  # database save raw data of long van 3 HDD 2T: port 27018
        "ENGINE": "djongo",
        "NAME": "raw_kline1m_future",
        "ENFORCE_SCHEMA": False,
        "CLIENT": {
            "host": "127.0.0.1",
            "port": 27017,
            "username": "crawler",
            "password": "crawler@1235",
            "authSource": "raw_kline1m_future",
            "authMechanism": "SCRAM-SHA-1",
        },
    },
    "raw_kline1m_spot": {  # database save raw data of long van 3
        "ENGINE": "djongo",
        "NAME": "raw_kline1m_spot",
        "ENFORCE_SCHEMA": False,
        "CLIENT": {
            "host": "127.0.0.1",
            "port": 27017,
            "username": "crawler",
            "password": "crawler@1235",
            "authSource": "raw_kline1m_spot",
            "authMechanism": "SCRAM-SHA-1",
        },
    },
    "backtest_data": {  # database to save data for backtest on longvan3
        "ENGINE": "djongo",
        "NAME": "backtest_data",
        "ENFORCE_SCHEMA": False,
        "CLIENT": {
            "host": "127.0.0.1",
            "port": 27017,
            "username": "crawler",
            "password": "crawler@1245",
            "authSource": "backtest_data",
            "authMechanism": "SCRAM-SHA-1",
        },
    },
    "stock_backtest_result": {
        "ENGINE": "djongo",
        "NAME": "stock_backtest_result",
        "ENFORCE_SCHEMA": False,
        "CLIENT": {
            "host": "127.0.0.1",
            "port": 27017,
            "username": "crawler",
            "password": "crawler@1235",
            "authSource": "stock_backtest_result",
        },
    },
    "backtest_data_1m": {  # database to save data for backtest on longvan3 HDD 2T: port 27018
        "ENGINE": "djongo",
        "NAME": "backtest_data_1m",
        "ENFORCE_SCHEMA": False,
        "CLIENT": {
            "host": "127.0.0.1",
            "port": 27017,
            "username": "crawler",
            "password": "crawler@1245",
            "authSource": "backtest_data_1m",
            "authMechanism": "SCRAM-SHA-1",
        },
    },
    "backtest_data_1m_custom": {  # database to save data for backtest on longvan3 HDD 2T: port 27018
        "ENGINE": "djongo",
        "NAME": "backtest_data_1m_custom",
        "ENFORCE_SCHEMA": False,
        "CLIENT": {
            "host": "127.0.0.1",
            "port": 27018,
            "username": "crawler",
            "password": "crawler@1245",
            "authSource": "backtest_data_1m_custom",
            "authMechanism": "SCRAM-SHA-1",
        },
    },
    "backtest_data_1m_spot": {  # database to save data for backtest on longvan3 HDD 2T: port 27018
        "ENGINE": "djongo",
        "NAME": "backtest_data_1m_spot",
        "ENFORCE_SCHEMA": False,
        "CLIENT": {
            "host": "127.0.0.1",
            "port": 27018,
            "username": "crawler",
            "password": "crawler@1245",
            "authSource": "backtest_data_1m_spot",
            "authMechanism": "SCRAM-SHA-1",
        },
    },
    "ftx_backtest_data": {  # database to save data for backtest on longvan3 HDD 2T: port 27018
        "ENGINE": "djongo",
        "NAME": "ftx_backtest_data",
        "ENFORCE_SCHEMA": False,
        "CLIENT": {
            "host": "127.0.0.1",
            "port": 27018,
            "username": "crawler",
            "password": "crawler@1235",
            "authSource": "ftx_backtest_data",
            "authMechanism": "SCRAM-SHA-1",
        },
    },
    "backtest_result": {  # database to save result for backtest on server 68
        "NAME": "coin_lab",
        "ENGINE": "django.db.backends.mysql",
        "CONN_MAX_AGE": 3600,
        "USER": "optimization",
        "PASSWORD": "0timization!@#QWEASDZXC",
        "HOST": "14.225.16.78",
        "PORT": 3324,
    },
    "backtest_data_stock": {  # database to save data for backtest on longvan3
        "ENGINE": "djongo",
        "NAME": "backtest_data",
        "ENFORCE_SCHEMA": False,
        "CLIENT": {
            "host": "127.0.0.1",
            "port": 27022,
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = "/public/"

# route for react frontend
REACT_APP_DIR = os.path.join(BASE_DIR, "frontend")

STATICFILES_DIRS = [
    os.path.join(REACT_APP_DIR, "build"),
]

# CORS_ORIGIN_WHITELIST = [
#     'http://192.168.68.26:3000',
# ]

CSRF_TRUSTED_ORIGINS = ["https://monitor.f5traders.com"]

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

LOGIN_URL = "/admin/login"

SECURE_SSL_REDIRECT = False
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

ALLOWED_HOSTS = [
    "monitor.f5traders.com",
]
